openapi: 3.0.1
info:
  title: Customer API
  version: '1.0'
  description: This API manages the customer accounts
  x-logo:
    url: ''
servers:
  - url: 'http://localhost:8081/api'
paths:
  /customer:
    summary: Customer Resource
    description: A customer resource
    get:
      tags: []
      operationId: get all customers
      summary: Get a list of all customer
      description: Getting a list of all customers
      responses:
        '200':
          description: Get all products successful
          content:
            application/json:
              schema:
                type: array
                description: 'Get all customers'
                items:
                  $ref: '#/components/schemas/Customer'
                example: ''
                externalDocs:
                  url: ''
                  description: ''
              encoding: ''
              example: ''
          x-last-modified: 1617178023946
          headers: {}
          links: {}
    post:
      tags: []
    x-last-modified: 1617177834079
  '/customer/{id}':
    summary: Specific Customer
    description: A resource that can make changes to a specific customer
    put:
      tags: []
    delete:
      tags: []
    x-last-modified: 1617177890822
components:
  schemas:
    Customer:
      description: A customer object
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        username:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        group:
          type: string
      x-last-modified: 1617177718900
  securitySchemes: {}
  headers: {}
  responses: {}
  parameters: {}
tags:
  - name: customer
    description: customer
    externalDocs: {}
    x-last-modified: 1617177923100
security: []
