openapi: 3.0.1
info:
  title: Customer API
  version: '1.0'
  description: This API manages the customer accounts
  x-logo:
    url: ''
servers:
  - url: 'http://localhost:8081/api'
paths:
  /customer:
    summary: Customer Resource
    description: A customer resource
    get:
      tags: []
      responses:
        '200':
          content:
            application/json:
              schema:
                description: Get all customers
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
                externalDocs:
                  description: ''
                  url: ''
                example: ''
              example: ''
          description: Get all products successful
          x-last-modified: 1617178023946
      operationId: get all customers
      summary: Get a list of all customer
      description: Getting a list of all customers
    post:
      tags: []
      operationId: create customer
      summary: Create a new customer
      description: Create a new customer account
      requestBody:
        description: C
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Customer created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          x-last-modified: 1617178458054
          headers: {}
          links: {}
        '422':
          description: Customer already exists
          x-last-modified: 1617178498150
    x-last-modified: 1617177834079
  '/customer/{id}':
    summary: Specific Customer
    description: A resource that can make changes to a specific customer
    put:
      tags: []
    delete:
      tags: []
    x-last-modified: 1617177890822
components:
  schemas:
    Customer:
      description: A customer object
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        username:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        group:
          type: string
      x-last-modified: 1617177718900
  securitySchemes: {}
  headers: {}
  responses: {}
  parameters: {}
tags:
  - name: customer
    description: customer
    externalDocs: {}
    x-last-modified: 1617177923100
security: []
