openapi: 3.0.1
info:
  title: Sale API
  version: '1.0'
  description: Manages Sales
  x-logo:
    url: ''
servers:
  - url: 'http://localhost:8081/api'
paths:
  /sale:
    summary: Sale Resource
    description: Sale
    post:
      requestBody:
        description: Send a new sale through as a JSON payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sale'
        required: false
      tags:
        - sale
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sale'
          description: Sale created successfully
          x-last-modified: 1617173509070
        '422':
          description: 'Sale not created, sale ID already exists'
          x-last-modified: 1617173605139
      operationId: create new sale
      summary: Creating a new sale
      description: This resource is able to create a new sale
    x-last-modified: 1617170575051
  '/sale/customer/{id}':
    summary: Customer sales
    description: Get sale details on a particular customer
    get:
      tags:
        - customer sale
      parameters:
        - deprecated: false
          name: id
          description: The customer's unique ID code
          schema:
            type: string
          in: path
          required: true
          x-last-modified: 1617223367761
      responses:
        '200':
          content:
            application/json:
              schema:
                description: ''
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
                externalDocs:
                  description: ''
                  url: ''
                example: ''
              example: ''
          description: Customer found
          x-last-modified: 1617174298660
        '404':
          description: Could not find customer
          x-last-modified: 1617175368928
      operationId: get all customer sales
      summary: Get all the customer sales
      description: This resource can return all the sales of the customer
    parameters:
      - deprecated: false
        name: id
        schema:
          type: string
        in: path
        required: true
        x-last-modified: 1618128442550
    x-last-modified: 1617173839984
  '/sale/customer/{id}/summary':
    get:
      tags:
        - customer sale
      parameters:
        - deprecated: false
          name: id
          description: Sale ID
          schema:
            type: string
          in: path
          required: true
          x-last-modified: 1618129471696
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
          description: Sale Found
          x-last-modified: 1618128995554
        '404':
          description: Sale Not Found
          x-last-modified: 1618129014165
    parameters:
      - deprecated: false
        name: id
        schema:
          type: string
        in: path
        required: true
        x-last-modified: 1618128558840
    x-last-modified: 1618128513828
  '/sale/{id}':
    delete:
      tags:
        - sale
      parameters:
        - deprecated: false
          name: id
          description: The Sale ID
          schema:
            type: string
          in: path
          required: true
          x-last-modified: 1618129511043
      responses:
        '204':
          description: Sale Deleted
          x-last-modified: 1618129058799
        '404':
          description: Sale not found
          x-last-modified: 1618129076792
    parameters:
      - deprecated: false
        name: id
        schema:
          type: string
        in: path
        required: true
        x-last-modified: 1618128635416
    x-last-modified: 1618128596612
components:
  schemas:
    Sale:
      description: A Sale object
      required:
        - id
      type: object
      properties:
        id:
          type: string
        saleDate:
          type: string
        customer:
          $ref: '#/components/schemas/Customer'
        items:
          type: array
          items:
            $ref: '#/components/schemas/SaleItem'
        totals:
          $ref: '#/components/schemas/Totals'
      x-last-modified: 1617170416003
    Customer:
      description: Return a specific Customer object by the customer's ID number
      required:
        - id
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        group:
          type: string
      x-last-modified: 1618128691636
    Summary:
      description: A summary object of a sale
      required:
        - id
      type: object
      properties:
        numberOfSales:
          type: integer
        totalPayment:
          type: number
        group:
          type: string
      x-last-modified: 1618130261803
    SaleItem:
      description: A SaleItem that the customer has purchased
      required:
        - id
      type: object
      properties:
        productID:
          type: string
        quantity:
          format: double
          type: number
        price:
          format: double
          type: number
      x-last-modified: 1618130288513
    Totals:
      description: Gives the total of a sale
      required:
        - id
      type: object
      properties:
        totalPrice:
          format: double
          type: number
        totalTax:
          format: double
          type: number
        totalPayment:
          format: double
          type: number
      x-last-modified: 1618130306040
  securitySchemes: {}
  headers: {}
  responses: {}
  parameters: {}
tags:
  - name: sale
    description: sale
    externalDocs:
      description: Nothing is here
      url: 'http://localhost:8081/swagger'
    x-last-modified: 1617223063459
  - name: customer sale
    x-last-modified: 1618132478581
    description: customer sale
security: []